name: opigno
recipe: drupal9

config:
  webroot: web
  php: '7.4'
  composer_version: '2'
  xdebug: false

env_file:
  - .env
  - .env.local

services:
  appserver:
    config:
      php: .lando/php.ini
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=opigno.lndo.site"
        ENV: "lando"
        DRUSH_OPTIONS_URI: "https://opigno.lndo.site"
        XDEBUG_MODE: "debug"
        XDEBUG_TRIGGER: 1
  node:
    type: node:12
    globals:
      gulp-cli: "latest"

tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  debug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  debug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root