# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{all}/":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: true
    default_ttl: 0
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']
    headers: ['Accept', 'Accept-Language']



"https://www.{all}/":
  type: redirect
  to: "https://{all}/"
